<a href="https://colab.research.google.com/github/harikrishnareddymallavarapu/PyTorch/blob/main/PyTorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [ ]:
torch.manual_seed(7)

In [ ]:
#initalising rand tensor that follows a normal distribution
x = torch.randn((1,2))
y = torch.randn(1,2)
x,y

(tensor([[2.6092, 0.0739]]), tensor([[-0.0219, -1.7810]]))

In [ ]:
x.shape, y.shape

(torch.Size([1, 2]), torch.Size([1, 2]))

In [21]:
#Creating a sigmoid activation function
def activation(x):
  return 1/(1+ torch.exp(-1*x))

In [4]:
features = torch.randn((1,5))
weights = torch.randn_like(features)
bias = torch.randn((1,1))

In [ ]:
#Direct multiplication of features and weights - not efficient
output = activation(torch.sum(features*weights)+bias) # can also be written as (features*weight).sum()
#however both multiplication and sum can be done using - torch.matmul or torch.mm, but torch.matmul doesnt return an error if the elelements are of not the same shape
output

tensor([[0.3345]])

In [45]:
torch.matmul(features, torch.randn(1,5).view(5,1))

tensor([[-3.2544]])

#Single Layer Nenural Network

In [ ]:
#Tenshor can be reshaped using reshape or resize
#weights.reshape(5,1) - returns a new tensor (sometimes it changes the memory location and returns a clone)
#weights.resize_(5,1) - '_' - inplace operator, if we request a shape that has more or less elements we will loose some records and doesnt return an error
#weights.view(5,1) - returns a new tensor, if elements doesnt match with requested size it returns error
output = activation(torch.mm(features, weights.view(5,1))+bias)
output

tensor([[0.3345]])

#Multi Layer Neural Network

###Assume 2 layers, Input layer - 5 input features, Hidden Layer - 2 neurons, output contaning one neuron



In [7]:
input = torch.randn((1,5))
input.shape

torch.Size([1, 5])

In [8]:
inputFeatureCount = input.shape[1]
hiddenNeuronCount = 2
ouputNeuronCount = 1

In [9]:
weightsLayer1 = torch.randn(inputFeatureCount,hiddenNeuronCount)
weightsLayer2 = torch.randn(hiddenNeuronCount,ouputNeuronCount)

In [12]:
print(weightsLayer2)
weightsLayer2.shape


tensor([[-0.3216],
        [-0.3656]])


torch.Size([2, 1])

In [13]:
print(weightsLayer1)
weightsLayer1.shape

tensor([[ 0.3687,  1.6291],
        [-0.2917, -0.7772],
        [-1.6031, -0.1650],
        [-0.9162, -0.6727],
        [-0.5082,  0.4909]])


torch.Size([5, 2])

In [14]:
biasLayer1 = torch.randn((1,hiddenNeuronCount))
biasLayer2 = torch.randn((1,ouputNeuronCount))

In [17]:
biasLayer1, biasLayer2

(tensor([[-0.6228, -0.1806]]), tensor([[-0.7136]]))

In [30]:
#Building the Neural Network

#Layer1
outputHiddenLayer1  = activation(torch.mm(input,weightsLayer1)+biasLayer1)
print(input.shape, weightsLayer1.shape, outputHiddenLayer1.shape)

torch.Size([1, 5]) torch.Size([5, 2]) torch.Size([1, 2])


In [32]:
#Layer2
outputHiddenLayer2  = activation(torch.mm(outputHiddenLayer1,weightsLayer2)+biasLayer2)
print(outputHiddenLayer1.shape, weightsLayer2.shape, outputHiddenLayer2.shape)

torch.Size([1, 2]) torch.Size([2, 1]) torch.Size([1, 1])


#Torch to Numpy and back
- Here after the conversion, memeory will be still shared between both the tensor and numpy, any inplace operation done on numpy or torch variable will result a change in both




In [33]:
import numpy as np

In [38]:
a = np.random.randn(1,4)
a

array([[-1.94903991,  1.55288357, -1.35340269, -0.22766433]])

In [42]:
b = torch.from_numpy(a)
b

tensor([[-1.9490,  1.5529, -1.3534, -0.2277]], dtype=torch.float64)

In [40]:
b = b*2
b,a

(tensor([[-3.8981,  3.1058, -2.7068, -0.4553]], dtype=torch.float64),
 array([[-1.94903991,  1.55288357, -1.35340269, -0.22766433]]))

In [44]:
b.numpy()

array([[-3.89807982,  3.10576714, -2.70680537, -0.45532865]])

In [43]:
b= b.mul_(2)
b,a

(tensor([[-3.8981,  3.1058, -2.7068, -0.4553]], dtype=torch.float64),
 array([[-3.89807982,  3.10576714, -2.70680537, -0.45532865]]))