<a href="https://colab.research.google.com/github/harikrishnareddymallavarapu/PyTorch/blob/main/PyTorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [ ]:
torch.manual_seed(7)

In [6]:
#initalising rand tensor that follows a normal distribution
x = torch.randn((1,2))
y = torch.randn(1,2)
x,y

(tensor([[2.6092, 0.0739]]), tensor([[-0.0219, -1.7810]]))

In [7]:
x.shape, y.shape

(torch.Size([1, 2]), torch.Size([1, 2]))

In [11]:
#Creating a sigmoid activation function
def activation(x):
  return 1/(1+ torch.exp(-1*x))

In [10]:
features = torch.randn((1,5))
weights = torch.randn_like(features)
bias = torch.randn((1,1))

In [12]:
#Direct multiplication of features and weights - not efficient
output = activation(torch.sum(features*weights)+bias)
output

tensor([[0.3345]])

In [14]:
#Tenshor can be reshaped using reshape or resize
output = activation(torch.mm(features, weights.view(5,1))+bias)
output

tensor([[0.3345]])

In [ ]:
weights = torch.randn(1,3)
bias = 